### ISSUE TITLE
metadata output file arg should have its full path passed

### ISSUE THREAD

**Issue by hiddenillusion** [matthewdunwoody/block-parser#4]
Based on the way [`output_result`](https://github.com/matthewdunwoody/block-parser/blob/master/block-parser/block-parser.py#L145) is written for the _metadata_ file || the way it's passed via [`main`](https://github.com/matthewdunwoody/block-parser/blob/master/block-parser/block-parser.py#L157), if the provided `args.metdata` string is just the filename and doesn't include its full path on the CLI then writing to it will fail.

example:

Running with these options:
```$ python block-parser.py -m parsed_powershell_metadata.csv -o parsed_powershell -a powershell.evtx```

with these tests:

```python
if m:
  if not os.path.isdir(os.path.dirname(m)):
    print(m)
    print(os.path.abspath(m))
    print(os.path.dirname(m))
    print(os.path.abspath(os.path.dirname(m)))
```

produces; the third line being the issue:

```
parsed_powershell_metadata.csv
/opt/compromised_system/parsed_powershell_metadata.csv

/opt/compromised_system
```

Simple enough to add in `main()` or keep where it is, but either way adding `os.path.abspath()` before will eliminate the error.

**Comment by matthewdunwoody** [comment]
Addressed as recommended. Thanks for submitting the issue
