### ISSUE TITLE
Unicode string error within to_lxml

### ISSUE THREAD

**Issue by hiddenillusion** [matthewdunwoody/block-parser#5]
I ran into the error "Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration." when trying to run this against a supported EVTX. 

Based on current code,  [`get_entries()`](https://github.com/matthewdunwoody/block-parser/blob/master/block-parser/block-parser.py#L82) grabs the lxml version within [`Entry`](https://github.com/matthewdunwoody/block-parser/blob/master/block-parser/block-parser.py#L57). `get_entries` catches the exception but based on the error, won't parse the record.

In disclosure, I didn't dig in enough to see if the issue should be handled by manually encoding within `etree.fromstring` or if this is a one-off situation where there's some unexpected code messing up the `<?xml... unicode=\"utf-8"...` that's already being declared but I can provide the EVTX offline if requested.

One quick solution that worked was just adding some exception handling to [`to_lxml`](https://github.com/matthewdunwoody/block-parser/blob/master/block-parser/block-parser.py#L31) and manually encoding.

e.g. - 

```python
def to_lxml(record_xml):
  """
  @type record: Record
  """
  try:
    return etree.fromstring("<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"yes\" ?>%s" %
      record_xml.replace("xmlns=\"http://schemas.microsoft.com/win/2004/08/events/event\"", ""))
  except:
    return etree.fromstring("<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"yes\" ?>%s" %
      record_xml.replace("xmlns=\"http://schemas.microsoft.com/win/2004/08/events/event\"", "").encode('utf-8')) 
```

**Comment by matthewdunwoody** [comment]
I incorporated your code verbatim, as you indicated that it resolved the issue you encountered and it appears unlikely to cause problems (and did not change the outcome of my testing). Thanks for submitting the issue!
